export function useEvents() {
  const config = useRuntimeConfig()

  return [
    { title: config.public.event1Title as string, subtitle: config.public.event1Subtitle as string, image: config.public.event1Image as string, heroImage: config.public.event1HeroImage as string, slug: config.public.event1Slug as string, orientation: config.public.event1Orientation as 'portrait' | 'landscape', type: config.public.event1Type as string, poster: config.public.event1Poster as string, photos: config.public.event1Photos as string },
    { title: config.public.event2Title as string, subtitle: config.public.event2Subtitle as string, image: config.public.event2Image as string, heroImage: config.public.event2HeroImage as string, slug: config.public.event2Slug as string, orientation: config.public.event2Orientation as 'portrait' | 'landscape', type: config.public.event2Type as string, poster: config.public.event2Poster as string, photos: config.public.event2Photos as string },
    { title: config.public.event3Title as string, subtitle: config.public.event3Subtitle as string, image: config.public.event3Image as string, heroImage: config.public.event3HeroImage as string, slug: config.public.event3Slug as string, orientation: config.public.event3Orientation as 'portrait' | 'landscape', type: config.public.event3Type as string, poster: config.public.event3Poster as string, photos: config.public.event3Photos as string },
    { title: config.public.event4Title as string, subtitle: config.public.event4Subtitle as string, image: config.public.event4Image as string, heroImage: config.public.event4HeroImage as string, slug: config.public.event4Slug as string, orientation: config.public.event4Orientation as 'portrait' | 'landscape', type: config.public.event4Type as string, poster: config.public.event4Poster as string, photos: config.public.event4Photos as string },
    { title: config.public.event5Title as string, subtitle: config.public.event5Subtitle as string, image: config.public.event5Image as string, heroImage: config.public.event5HeroImage as string, slug: config.public.event5Slug as string, orientation: config.public.event5Orientation as 'portrait' | 'landscape', type: config.public.event5Type as string, poster: config.public.event5Poster as string, photos: config.public.event5Photos as string },
    { title: config.public.event6Title as string, subtitle: config.public.event6Subtitle as string, image: config.public.event6Image as string, heroImage: config.public.event6HeroImage as string, slug: config.public.event6Slug as string, orientation: config.public.event6Orientation as 'portrait' | 'landscape', type: config.public.event6Type as string, poster: config.public.event6Poster as string, photos: config.public.event6Photos as string },
  ]
}
